[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
raffle = "649vJ9q8JBKY7pvc5Uspwf6diESX4qKKjVQ1DTCubNQX"

[programs.localnet]
raffle = "649vJ9q8JBKY7pvc5Uspwf6diESX4qKKjVQ1DTCubNQX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./deploy-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
